### PR TITLE
Update issue templates for github

### PR DESCRIPTION
**Pull request by fenilgandhi**

### CODE REVIEW

**Comment by rishabh1403** [comment]
I think there's a issue template .md file for this?

**Comment by fenilgandhi** [comment]
Yes, this is just a specific feature provided by github for storing all files in one `.github` folder. Do you want me to switch to the generic way of using ISSUE_TEMPLATES.md ?

**Comment by rishabh1403** [comment]
Yes

**Comment by fenilgandhi** [comment]
Ok, i have updated the template location.

**Pull request closed without merging**
