### PR TITLE
Booking Api's

### LINKED ISSUE #57: [feat] Booking-API's
### **Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]]

### **Describe the solution you'd like**
[A clear and concise description of what you want to happen. Add any considered drawbacks.]

### **Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.]

### **Additional context**
[Add any other context or screenshots about the feature request here. Maybe a screenshot or design ?]

### PR DESCRIPTION
**Pull request by ViralRuparel**
# Description

Added booking api's to book, cancel booking, list bookings, and get booked slots with 100% test coverage.

Fixes #57 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

### Checklist for opening a PR
Please, go through these steps before you open a PR.
- [x] I have created an issue for this PR.
- [x] I have properly named the Pull request with **[tag]** before the name of PR.
- [x] **I am choosing the correct base branch to merge**. 

### Checklist for submitting your PR
Please, go through these steps before you resolve you **[WIP]** status.
- [x] I have implemented the functions and relevant test cases.
- [x] All my test cases are passing.
- [x] I have made corresponding changes to the documentation
- [x] I have rebased my branch.
- [x] I have added atleast 2 reviewers 
- [x] I have provided a description of changes.
- [x] I have attached relevant screenshots/gifs ( if UI has changed.)
- [x] I have only one commit. (if not, squash them into one commit).
- [x] I have added `closes #XXXX` in my comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by ViralRuparel** [comment]
#57

**Comment by ViralRuparel** [comment]
Error in the location test cases which is already merged in the master, Please check circle ci report, no errors in my booking api's.

**Review by nimish-gupta — APPROVED** [review]
LGTM.

**Review by vineetvk01 — APPROVED** [review]
LGTM

**Pull request merged**
