### PR TITLE
View of Workspace list after search

### PR DESCRIPTION
**Pull request by vineetvk01**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

### Checklist for opening a PR
Please, go through these steps before you open a PR.
- [ ] I have created an issue for this PR.
- [ ] I have properly named the Pull request with **[tag]** before the name of PR.
- [ ] **I am choosing the correct base branch to merge**. 

### Checklist for submitting your PR
Please, go through these steps before you resolve you **[WIP]** status.
- [ ] I have implemented the functions and relevant test cases.
- [ ] All my test cases are passing.
- [ ] I have made corresponding changes to the documentation
- [ ] I have rebased my branch.
- [ ] I have added atleast 2 reviewers 
- [ ] I have provided a description of changes.
- [ ] I have attached relevant screenshots/gifs ( if UI has changed.)
- [ ] I have only one commit. (if not, squash them into one commit).
- [ ] I have added `closes #XXXX` in my comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by vineetvk01** [comment]
view

**Comment by vineetvk01** [comment]
Screenshot from 2020-02-21 18-17-11

**Comment by vineetvk01** [comment]
loader-op

**Comment by vineetvk01** [comment]
loader-op

**Review by nitishmittal1990 — COMMENTED** [review]
Please fix test issue of workspace model

**Review by nimish-gupta — APPROVED** [review]
LGTM.

**Review by ViralRuparel — APPROVED** [review]
LGTM

**Review by ViralRuparel — DISMISSED** [review]
please solve the errors check circleci report

**Review by nitishmittal1990 — APPROVED** [review]
LGTM!

**Pull request merged**
