### PR TITLE
[feat] Add Login View

### LINKED ISSUE #62: [feat] Implement Login View
### **Is your feature request related to a problem? Please describe.**
Implement a Login/Signup Page for an unauthenticated user.

### **Describe the solution you'd like**
 A complete implementation should have the following features:
- A response login form with validations.
- Auto redirect for authenticated users.
- API Integration
- Test Cases.

### **Describe alternatives you've considered**
\-

### **Additional context**
\-

### PR DESCRIPTION
**Pull request by fenilgandhi**
# Description
Implements a Login Component with a Login View. 

Fixes Github Issue #62 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

### Checklist for opening a PR
Please, go through these steps before you open a PR.
- [x] I have created an issue for this PR.
- [x] I have properly named the Pull request with **[tag]** before the name of PR.
- [x] **I am choosing the correct base branch to merge**. 

### Checklist for submitting your PR
Please, go through these steps before you resolve you **[WIP]** status.
- [ ] I have implemented the functions and relevant test cases.
- [ ] All my test cases are passing.
- [ ] I have made corresponding changes to the documentation
- [ ] I have rebased my branch.
- [ ] I have added atleast 2 reviewers 
- [ ] I have provided a description of changes.
- [ ] I have attached relevant screenshots/gifs ( if UI has changed.)
- [ ] I have only one commit. (if not, squash them into one commit).
- [ ] I have added `closes #XXXX` in my comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by fenilgandhi** [comment]
Here's how the login form looks in different screen sizes.
login-responsive

**Comment by fenilgandhi** [comment]
And here's how it responds to user events.
ezgif-7-c2ba8bbf9f7a

**Comment by fenilgandhi** [comment]
@rishabh1403, CI checks are passing, deploy preview are failing because it needs #39 to be merged.

**Review by nimish-gupta — APPROVED** [review]
LGTM

**Review by ViralRuparel — APPROVED** [review]

**Pull request merged**
